/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import komunikacija.Komunikacija;
import model.KlijentskiZahtev;
import model.ModelTabeleGazdinstvo;
import model.ModelTabelePreduzeca;
import model.Operacije;
import model.PoljoprivrednoGazdinstvo;
import model.PoljoprivrednoPreduzece;
import model.ServerskiOdgovor;
import niti.GazdinstvoNit;
import niti.PreduzeceNit;


/**
 *
 * @author Miloš
 */
public class GazdinstvoForma extends javax.swing.JFrame {
    private List<PoljoprivrednoGazdinstvo>gazdinstva;
    private List<PoljoprivrednoGazdinstvo>pom;
    int jezik=0;

    public int getJezik() {
        return jezik;
    }

    public void setJezik(int jezik) {
        this.jezik = jezik;
    }
    public List<PoljoprivrednoGazdinstvo> getGazdinstvo() {
        return gazdinstva;
    }

    public void setGazdinstvo(List<PoljoprivrednoGazdinstvo> gazdinstva) {
        this.gazdinstva = gazdinstva;
        this.pom=gazdinstva;
    }
    
    /**
     * Creates new form PreduzeceForma
     */
    public GazdinstvoForma() {
        initComponents();
        GazdinstvoNit gn=new GazdinstvoNit(jTable1,this);
        gn.start();
        ListSelectionModel selectionModel = jTable1.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        try {
            selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int izabrani = jTable1.getSelectedRow();
                    if (izabrani != -1) {
                       PoljoprivrednoGazdinstvo rk=pom.get(izabrani);
                       jTextField1.setText(rk.getNazivKooperanta());
                       jTextField2.setText(rk.getMesto());
                       jTextField3.setText(rk.getVlasnikGaz());
                       jTextField4.setText(String.valueOf(rk.getBrojTelefona()));
                    
                    }
                
                
                }
            }
        });
        } catch (Exception e) {
        }
        jComboBox1.removeAllItems();
        jComboBox1.addItem("SRB");
        jComboBox1.addItem("ENG");
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedItem = (String) jComboBox1.getSelectedItem();

                    if ("SRB".equals(selectedItem)) {
                    jLabel3.setText("Vlasnik");
                    jLabel1.setText("Naziv");
                    jLabel2.setText("Mesto");
                    jLabel4.setText("Br tel");
                    jLabel5.setText("Jezik :");
                    jButton1.setText("Unesi gazdinstvo");
                    jButton2.setText("Izmeni gazdinstvo");
                    jButton3.setText("Obrisi gazdinstvo");
                    jButton4.setText("Pretrazi gazdinstvo");
                    jButton5.setText("Nazad");
                    //jButton1.setText("Uloguj se");
                    jezik=0;
                } else if ("ENG".equals(selectedItem)) {
                    jLabel3.setText("Owner");
                    jLabel1.setText("Name");
                    jLabel2.setText("Hometown");
                    jLabel4.setText("Phone");
                    jLabel5.setText("Language :");
                    jButton1.setText("Insert holding");
                    jButton2.setText("Update holding");
                    jButton3.setText("Delete holding");
                    jButton4.setText("Search holding");
                    jButton5.setText("Back");
                    jezik=1;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("Mesto");

        jLabel3.setText("Vlasnik");

        jLabel4.setText("Broj tel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Unesi gazdinstvo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Izmeni gazdinstvo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Obrisi gazdinstvo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Pretrazi gazdinstvo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nazad");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Jezik :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String naziv=jTextField1.getText();
        String mesto=jTextField2.getText();
        String vlasnik=jTextField3.getText();
        String brtel=jTextField4.getText();
        

        PoljoprivrednoGazdinstvo pg=new PoljoprivrednoGazdinstvo(vlasnik, brtel, -1, naziv, mesto);
        kreirajPoljoprivrednoGazdinstvo(pg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int izabrani=jTable1.getSelectedRow();
        if(izabrani==-1&&jezik==0){
            JOptionPane.showMessageDialog(this, "Morate izabrati gazdinstvo", "Greska", JOptionPane.WARNING_MESSAGE);
            return;
        }if(izabrani==-1&&jezik==1){
            JOptionPane.showMessageDialog(this, "You have to choose holding", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        PoljoprivrednoGazdinstvo pg=pom.get(izabrani);
        boolean uspeh=obrisiPoljoprivrednoGazdinstvo(pg);
        if(uspeh){
           if (jezik==0) JOptionPane.showMessageDialog(this, "Gazdinstvo je uspesno obrisano","Potvrda",JOptionPane.INFORMATION_MESSAGE);
           else JOptionPane.showMessageDialog(this, "Holding is successfully deleted","Confirmation",JOptionPane.INFORMATION_MESSAGE);            


        }
        else{
        if(jezik==0)JOptionPane.showMessageDialog(this, "Sistem nije uspesno izvrsio brisanje","Potvrda",JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this, "Holdicn could not be deleted","Error",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int izabrani=jTable1.getSelectedRow();
        if(izabrani==-1){
            if(jezik==0){
                JOptionPane.showMessageDialog(this, "Morate izabrati gazdinstvo", "Greska", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else{
               JOptionPane.showMessageDialog(this, "You have to choose holding", "Error", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
        }
        PoljoprivrednoGazdinstvo pg=pom.get(izabrani);
        boolean uspeh=promeniPoljoprivrednoGazdinstvo(pg);
        if(uspeh){
            if(jezik==0){            
                JOptionPane.showMessageDialog(this, "Gazdinstvo je uspesno promenjeno","Potvrda",JOptionPane.INFORMATION_MESSAGE);
            }
            else  JOptionPane.showMessageDialog(this, "Holding is successfully updated","Confirmation",JOptionPane.INFORMATION_MESSAGE);

        }
        else{
            if(jezik==0)
            JOptionPane.showMessageDialog(this, "Sistem nije uspesno izvrsio promenu","Potvrda",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this, "Holding could not be updated","Error",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String naziv=jTextField1.getText();
        String mesto=jTextField2.getText();
        String vlasnik=jTextField3.getText();
        String brtel=jTextField4.getText();
        

        List<Object>params=new ArrayList<>();
        params.add(naziv);
        params.add(mesto);
        params.add(vlasnik);
        params.add(brtel);
        

        vratiListuPoljoprivrednoGazdinstvo(params, pom);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void kreirajPoljoprivrednoGazdinstvo(PoljoprivrednoGazdinstvo pg) {
        boolean ispravan=proveriGazdinstvo(pg);
        if(ispravan){
            KlijentskiZahtev kz=new KlijentskiZahtev(Operacije.DODAJGAZ, pg);
            komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();
            boolean uspeh=(boolean) so.getOdgovor();
            if(uspeh){
                if(jezik==0)
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio gazdinstvo");
                else JOptionPane.showMessageDialog(this, "System has saved the holding");

            }
            else{
                if(jezik==0)
                JOptionPane.showMessageDialog(this, "Sistem nije zapamtio gazdinstvo","Greska",JOptionPane.ERROR_MESSAGE);
                else JOptionPane.showMessageDialog(this, "System could not save the holding","Error",JOptionPane.ERROR_MESSAGE);

            }
            return;
        }
        else{
            if(jezik==0)
            JOptionPane.showMessageDialog(this, "Uneli ste nedozvoljenu vrednost polja","Greska",JOptionPane.ERROR_MESSAGE);
            else JOptionPane.showMessageDialog(this, "You have entered disallowed value","Error",JOptionPane.ERROR_MESSAGE);

        }
    }

    private boolean proveriGazdinstvo(PoljoprivrednoGazdinstvo pg) {
        if(!pg.getMesto().matches("[A-Za-z ]+"))return false;
        if(!pg.getNazivKooperanta().matches("[A-Za-z ]+"))return false;
        if(!pg.getBrojTelefona().matches("(06)[0-90]+"))return false;
        if(pg.getBrojTelefona().length()>12||pg.getBrojTelefona().length()<8)return false;
        return true;

        
    }

    private boolean promeniPoljoprivrednoGazdinstvo(PoljoprivrednoGazdinstvo pg) {
        pg.setNazivKooperanta(jTextField1.getText());
        pg.setMesto(jTextField2.getText());
        pg.setVlasnikGaz(jTextField3.getText());
        pg.setBrojTelefona(jTextField4.getText());
        
        boolean provera=proveriGazdinstvo(pg);
        if(!provera){
            return provera;
        }
        KlijentskiZahtev kz=new KlijentskiZahtev(Operacije.IZMENIGAZ, pg);
        
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();
        boolean uspeh=(boolean) so.getOdgovor();
        return uspeh;
    }

    private boolean obrisiPoljoprivrednoGazdinstvo(PoljoprivrednoGazdinstvo pg) {
        KlijentskiZahtev kz=new KlijentskiZahtev(Operacije.OBRISIGAZ, pg);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();
        boolean uspeh=(boolean) so.getOdgovor();
        return uspeh;
    }

    private void vratiListuPoljoprivrednoGazdinstvo(Object kriterijumRukovodilacKooperacije, List<PoljoprivrednoGazdinstvo> pom) {
        List<Object>params=(List<Object>) kriterijumRukovodilacKooperacije;
        String naziv=(String) params.get(0);
        String mesto=(String) params.get(1);
        String vlasnik=(String) params.get(2);
        String brtel=(String) params.get(3);
        
        pom=new ArrayList<>();
        for (PoljoprivrednoGazdinstvo gazdinstvo : gazdinstva) {
            if(gazdinstvo.getNazivKooperanta().contains(naziv)&&gazdinstvo.getMesto().contains(mesto)&&gazdinstvo.getVlasnikGaz().contains(vlasnik)&&gazdinstvo.getBrojTelefona().contains(brtel)){
                pom.add(gazdinstvo);
            }
        }
        if(pom.isEmpty()){
            if(jezik==0)
            JOptionPane.showMessageDialog(this, "Sistem nije pronasao vrednosti po zadatom kriterijumu");
            else JOptionPane.showMessageDialog(this, "System could not find values for given criteria");

            return;
        }
        this.pom=pom;
        ModelTabeleGazdinstvo mtr=new ModelTabeleGazdinstvo(pom,jezik);
        jTable1.setModel(mtr);
    }
}
