/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import komunikacija.Komunikacija;
import model.KlijentskiZahtev;
import model.ModelTabelePrikaziStavku;
import model.ModelTabeleStavka;
import model.Operacije;
import model.PoljoprivrednaKultura;
import model.PoljoprivrednoGazdinstvo;
import model.PoljoprivrednoPreduzece;
import model.Potvrda;
import model.RukovodilacKooperacije;
import model.ServerskiOdgovor;
import model.StavkaPotvrde;

/**
 *
 * @author Miloš
 */
public class PrikaziPotvrduForma extends javax.swing.JFrame {
    Potvrda p;
    List<RukovodilacKooperacije>rukovodioci;
    List<PoljoprivrednoPreduzece>preduzeca;
    List<PoljoprivrednoGazdinstvo>gazdinstva;
    int jezik=0;
    /**
     * Creates new form PrikaziPotvrduForma
     */
    public PrikaziPotvrduForma(Potvrda p,List<RukovodilacKooperacije>rukovodioci,List<PoljoprivrednoPreduzece>preduzeca,List<PoljoprivrednoGazdinstvo>gazdinstva) {
        initComponents();
        this.p=p;
        this.gazdinstva=gazdinstva;
        this.rukovodioci=rukovodioci;
        this.preduzeca=preduzeca;
        postaviStaticke(this.p);
        popuniTabelu();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("SRB");
        jComboBox1.addItem("ENG");
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedItem = (String) jComboBox1.getSelectedItem();

                    if ("SRB".equals(selectedItem)) {
                    jLabel3.setText("Datum vazenja");
                    jLabel1.setText("Datum izdavanja");
                    jLabel5.setText("Ukupan iznos");
                    jLabel7.setText("Rukovodilac");
                    jLabel9.setText("Kooperant");
                    jLabel11.setText("Jezik :");
                    jButton1.setText("Nazad");
                    
                    
                    jezik=0;
                } else if ("ENG".equals(selectedItem)) {
                    jLabel3.setText("Date of issue");
                    jLabel1.setText("Date of validity");
                    jLabel5.setText("Total");
                    jLabel7.setText("Manager");
                    jLabel9.setText("Cooperant");
                    jLabel11.setText("Language :");
                    jButton1.setText("Back");
                    
                    jezik=1;
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Nazad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum izdavanja");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Datum vazenja");

        jLabel4.setText("jLabel4");

        jLabel5.setText("Ukupan iznos");

        jLabel6.setText("jLabel6");

        jLabel7.setText("Rukovodilac");

        jLabel8.setText("jLabel8");

        jLabel9.setText("Kooperant");

        jLabel10.setText("jLabel10");

        jLabel11.setText("Jezik :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    private void postaviStaticke(Potvrda p) {
        SimpleDateFormat format=new SimpleDateFormat("dd.MM.yyyy");
        jLabel2.setText(format.format(p.getDatumIzdavanja()));
        jLabel4.setText(format.format(p.getDatumVazenja()));
        jLabel6.setText(p.getUkupanIznos()+"");
       
        for (RukovodilacKooperacije rukovodilacKooperacije : rukovodioci) {
            if(rukovodilacKooperacije.getId()==p.getIdRukovodilac()){
                jLabel8.setText(rukovodilacKooperacije.getIme()+" "+rukovodilacKooperacije.getPrezime());
            }
        }
        if(p.getKoopFlag()==0){
            for (PoljoprivrednoPreduzece poljoprivrednoPreduzece : preduzeca) {
                if(poljoprivrednoPreduzece.getIdKooperant()==p.getIdKooperant()){
                    jLabel10.setText(poljoprivrednoPreduzece.getNazivKooperanta());
                }
            }
        }
        else{
            for (PoljoprivrednoGazdinstvo gazdinstvo : gazdinstva) {
                if(gazdinstvo.getIdKooperant()==p.getIdKooperant()){
                    jLabel10.setText(gazdinstvo.getNazivKooperanta());
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        KlijentskiZahtev kz=new KlijentskiZahtev(Operacije.VRATISTA, p);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();
        List<StavkaPotvrde>stavke=(List<StavkaPotvrde>) so.getOdgovor();
        KlijentskiZahtev kz2=new KlijentskiZahtev(Operacije.VRATIKUL, null);
        Komunikacija.getInstance().posaljiZahtev(kz2);
        ServerskiOdgovor so2=Komunikacija.getInstance().primiOdgovor();
        List<PoljoprivrednaKultura>kulture=(List<PoljoprivrednaKultura>) so2.getOdgovor();
        List<String>nazivi=new ArrayList<>();
        for (StavkaPotvrde stavkaPotvrde : stavke) {
            System.out.println(stavkaPotvrde.getIznos());
            for (PoljoprivrednaKultura poljoprivrednaKultura : kulture) {
                if(poljoprivrednaKultura.getIdKultura()==stavkaPotvrde.getIdKultura()){
                    nazivi.add(poljoprivrednaKultura.getNazivKulture());
                    break;
                }
            }
        }
        ModelTabelePrikaziStavku mts=new ModelTabelePrikaziStavku(stavke, nazivi,jezik);
        jTable1.setModel(mts);
    }
}
